### PR TITLE
Avoid rmarkdown halt for pdf output

### PR DESCRIPTION
**Pull request by florisvdh**
Always allow HTML-specific content, also when generating PDF output. Before, rmarkdown complained and halted.

### CODE REVIEW

**Comment by ThierryO** [comment]
What happens with the HTML output in the pdf version?

**Comment by florisvdh** [comment]
With the current `master` branch, when I press 'build book' in RStudio, I get the following error:

```
output file: INBOmd_rapport.knit.md

Error: Functions that produce HTML output found in document targeting latex output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

  always_allow_html: yes

Note however that the HTML output will not be visible in non-HTML formats.

In addition: Warning message:
In plyr::split_indices(scale_id, n) :
  '.Random.seed' is not an integer vector but of type 'NULL', so ignored
Execution halted

Exited with status 1.
```

I don't know which pieces are (perhaps) affected. After adding the recommended setting, [this is the pdf output](https://github.com/inbo/inbomd_examples/files/1084297/INBOmd_rapport.pdf).

**Comment by ThierryO** [comment]
I can't reproduce the problem. Please check that you have a recent version of rmarkdown and webshot packages installed.

**Comment by ThierryO** [comment]
As I expected, the screenshot of the HTML is not taken. Probably because you don't have the webshot package installed. See https://bookdown.org/yihui/bookdown/html-widgets.html

**Pull request closed without merging**
